---
title: "People Analytics"
subtitle: "A Conversation"
format: 
  revealjs:
    theme: [default, theme.scss] 
    css: style.css
---

## What is People Analytics?

Anyone have their own definition? Art? 

## People Analytics == Workforce Analytics?

>Workforce analytics is the discovery, interpretation, and communication of meaningful patterns in workforce-related data to inform decision making and improve performance.^[Guenole, N., Ferrar, J., & Feinzig, S. (2017). The power of people: Learn how successful organizations use workforce analytics to improve business performance. Pearson Education, Inc.]

## People Analytics and Measurement at McKinsey 

* We are a multi-team system grouped into functional pods: 
  + BI Personnel Pod
  + BI Recruiting Pod
  + Data Engineering Pod
  + Data Science Pod [Alex's Pod]
  + Dev & ML Ops Pod
  + Translator Pod [Art's Pod]

## Common Components of a People Analytics Group

* People Data Team (DE Pod for PAM)
* PA Products Team (Dev Pod for PAM)
* PA Insights Team (Translator Pod for PAM)
* Advanced Analytics & Data Science (Data science & ML Pods for PAM)^[Garbis, N. (2022). Blueprint for building a people analytics team [White paper]. One Model. https://www.onemodel.co/whitepapers/blueprint-pa-team]

# Data Science in People Analytics

## Modeling People Is Hard 

>Modeling people presents a challenge because while models require low-dimensional representations, people defy simple characterizations. People are *diverse*, we are *socially influenced*, we are *error-prone*, we are *purposive*, and we *learn*. In addition, people possess *agency*--we have the capacity to act (p. 46).^[Page, S. E. (2018). The model thinker. Basic Books.]

## Methods in People Analytics
```{r echo=FALSE}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(tibble)

n_lm <- 30
jitter_seed <- 100

df <- tibble::tibble(
  METHOD = c(
    "Linear Regression",
    "Logistic Regression",
    "Poisson Regression",
    "Generalized Linear Models",
    "Generalized Linear Mixed-Effects Models",
    "Survival Regression Models",
    "Decision Trees",
    "Random Forests",
    "Deep Learning Models",
    "Topic Models (NLP)",
    "Network Analysis",
    "Confirmatory Factor Analysis",
    "Clustering Methods",
    "Exploratory Factor Analysis"
  ),
  # 1 - Very easily explained
  # 2 - Somewhat easily explained
  # 3 - Moderately difficult to explain
  # 4 - Hard to explain
  # 5 - Good luck
  EXPLAINABLE = c(
    1, 2, 2, 2,
    3, 3, 1, 4,
    5, 4, 3, 3, 
    3, 3
  ),
  MODEL_OVERSIGHT = c(
    1, 1, 1, 1,
    2, 2, 2, 3,
    3, 3, 2, 2, 
    3, 3
  ),
  SAMPLE = c(
    n_lm, 5*n_lm, 5*n_lm, 5*n_lm,
    10*n_lm, 8*n_lm, 10*n_lm, 50*n_lm,
    75*n_lm, 75*n_lm, 20*n_lm, 10*n_lm, 
    10*n_lm, 10*n_lm
  ),
  ML_CLASS = c(
    rep("Supervised", 9), "Mixed", "Mixed", "Supervised", "Unsupervised",
    "Unsupervised"
  )
)

ggplot2::ggplot(
  data = df,
  ggplot2::aes(
    x = MODEL_OVERSIGHT,
    y = EXPLAINABLE,
    color = ML_CLASS,
    size = SAMPLE
  )
) +
  ggplot2::theme_minimal() +
  ggplot2::geom_point(position = position_jitter(seed = jitter_seed)) +
  ggplot2::scale_size(guide = "none") +
  ggplot2::labs(
    x = "Technical Cost of the Model (Modeler Time + Estimation Time)",
    y = "Difficulty Communicating Results",
    color = "Type of ML Model"
  ) +
  ggrepel::geom_label_repel(aes(label = METHOD, x = MODEL_OVERSIGHT, y = EXPLAINABLE,
                                color = ML_CLASS),
                            box.padding   = 0.35, 
                            point.padding = 0.5,
                            segment.color = 'grey50',
                            inherit.aes = FALSE,
                            position = position_jitter(seed = jitter_seed)) +
  ggplot2::scale_x_continuous(
    labels = c("Cheap", "Expensive"),
    breaks = c(1, 3)
  ) +
  ggplot2::scale_y_continuous(
    labels = c("Easy", "Moderate" ,"Hard"),
    breaks = c(1.25, 3.125, 5)
    )
```

## Three Important Behavioral Data Science Topics

It's important to consider the following three (broad) topics whenever you start a new project: 

* The importance of measurement. 
* The limits of statistical models and the role of theory. 
* The importance of ethical AI (ethical risk mitigation).

## Use Case 1: Selection System Development

You're a manager of a People Analytics team at a large software engineering firm and your team has been tasked with overhauling the systems in place to select their entry-level software engineer role. You've been given the following three goals: 

1. Hire employees who will be top performers
2. Increase the diversity of the organization's hires
3. Reduce selection costs

## Use Case 2: Retention Analytics

Your team has been tasked with understanding why the organization is experiencing such high turnover among its entry-level software engineers. You've been given the following goals: 

1. Discover the factors driving entry-level software engineer attrition
2. Provide recommendations for interventions to improve retention
3. Estimate the financial impact of attrition

# Thanks!
